INSERT INTO festivo (dia, mes, nombre, tipo, dias_pascua) VALUES
(1, 1, 'Año nuevo', 1, null),
(6, 1, 'Santos Reyes', 2, null),
(19, 3, 'San José', 2, null),
(null, null, 'Jueves Santo', 3, -3),
(null, null, 'Viernes Santo', 3, -2),
(null, null, 'Domingo de Pascua', 3, 0),
(1, 5, 'Día del Trabajo', 1, null),
(null, null, 'Ascensión del Señor', 4, 40),
(null, null, 'Corpus Christi', 4, 61),
(null, null, 'Sagrado Corazón de Jesús', 4, 68),
(29, 6, 'San Pedro y San Paulo', 2, null),
(20, 7, 'Independencia Colombia', 1, null),
(7, 8, 'Batalla de Boyacá', 1, null),
(15, 8, 'Asunción de la Virgen', 2, null),
(12, 10, 'Día de la Raza', 2, null),
(1, 11, 'Todos los santos', 2, null),
(11, 11, 'Independencia de Cartagena', 2, null),
(8, 12, 'Inmaculada Concepción', 1, null),
(25, 12, 'Navidad', 1, null);
